# Site
repository: saemu/saemu.github.io
favicon: images/favicon.ico
darkmode: true
version: 2

# Personal info
name: Samuel Brand
title: C++ Software Engineer
email: jobs@samuelbrand.ch
website: www.samuelbrand.ch

# Social links
linkedin_username: brandsamuel

# About Section
about_title: Über mich
about_profile_image: images/profile.jpg
about_content: |
  _C++11 and beyond with Modern CMake_

  Das nächste Release der Software bereitet Ihnen schlaflose Nächte und treibt Ihnen die Schweißperlen auf die Stirn?

  Ich unterstütze Sie dabei die Testbarkeit der Source Code Basis zu erhöhen, die Tests zu automatisieren und das Deployment zu automatisieren.

  Durch die gelebten Clean Code Praktiken und Prinzipien werden Sie in Zukunft einem neuem Release gelassen entgegen schauen.

content:
  - title: Berufliche Erfahrung
    layout: list
    content:
      - layout: top
        title: KSP Kanzlei Dr. Seegers, Dr. Frankenheim Rechtsanwaltsgesellschaft mbH
        sub_title: Leading Software Engineer
        caption: November 2020 bis jetzt
        link: www.ksp.de
        description: |
          Inhouse Qt5 und C++ Software Entwicklung.
          
          Einführung von eines Software Entwicklungprozesses mit <mark>GitLab</mark>.

      - layout: top
        title: cubeware GmbH
        sub_title: C++ Software Engineer
        caption: Dezember 2019 bis Oktober 2020
        link: www.cubeware.com
        description: |
          <mark>C++14</mark> Software Entwicklung im verteilten Produktentwicklungsteam, Zusammenarbeit mit Microsoft Teams und <mark>Atlassian Confluence</mark>.
          Implementation neuer Features und Bugfixing für ETL Applikation des Business Intelligence Systems mit Microsoft Visual Studio und TFS.

      - layout: top
        title: Dermalog Identification Systems GmbH
        link: www.dermalog.com
        sub_title: Systems Engineer
        caption: Juli 2015 bis Dezember 2019
        description: |
          Software Entwicklung im Backend Produkt Team mit C++14 mit <mark>Enterprise Linux</mark> als Platform.
          
          Implementation und Testen von verteilten und hochverfügbaren Backend Services für biometrische Identifikationssysteme
          mit C++14, <mark>CMake</mark>, Google Protobuf und ZeroMQ. Entwicklungsprozess nach <mark>KANBAN</mark> abgebildet mit <mark>Atlassian JIRA</mark>.
          Automatisierung der Software Builds mit <mark>Git</mark>, Gerrit Codereview, Jenkins CI und Linux Docker Container.
          Software Paketierung mit <mark>RPM</mark> und automatisches Deployment mit <mark>Puppet</mark>.
          Etablierung von <mark>Clean Code</mark> Praktiken und Tugenden. Software Dokumentation mit Atlassian Confluence.
          
          Troubleshooter für Linux

      - layout: top
        title: RUAG Schweiz AG, RUAG Aviation
        sub_title: Software Engineer
        link: www.ruag.com
        caption: März 2010 bis Juni 2015
        description: |
          Software Entwicklung im Projekt Team mit C++11 unter Red Hat Enterprise Linux.
          
          Analyse und Design neuer Anforderungen für das Taktisches Ground Support System für die F/A-18 der Schweizer Luftwaffe mit <mark>IBM Telelogic DOORS</mark>.
          Implementation neuer Features und Bugfixes mit C++11, <mark>Qt4</mark> und ICS BX Pro. Software Versionierung mit Perforce.
          
          Troubleshooter für Linux

      - layout: top
        title: RUAG Aerospace AG
        sub_title: Software Entwickler
        link: www.ruag.com
        caption: März 2008 bis Februar 2010
        description: |
          Software Entwicklung im Projekt Team.
          
          Implementation neuer Features und Bugfixes mit C++03 und ICS BX Pro.

      - layout: top
        title: RUAG Aerospace AG
        sub_title: Praktikant
        link: www.ruag.com
        caption: September 2007 bis Februar 2008
        description: |
          Praktikum in der Software Entwicklung.

  - title: Ausbildung
    layout: list
    content:
      - layout: top
        title: Berner Fachhochschule
        sub_title: Bachelor of Science BFH
        caption: 2010 - 2013
        description: |
          Informatik Studium mit Vertiefung in Computer Perception and Virtual Reality.

      - layout: top
        title: Sulzer Textil AG
        sub_title: Polymechaniker
        caption: 1998 - 2002
        description: |
          Ausbildung zum Polymechaniker mit Vertiefung in Elektrotechnik
          
          Berufsmaturität GIBB Solothurn

  - title: IT Kenntnisse
    layout: list
    content:
      - layout: top
        title: Experte
        description: C++, CMake, Boost, GNU/Linux, Docker, Puppet, Git, Qt

      - layout: top
        title: Fortgeschritten
        description: Jetbrains IDEs, Clean Code, Apple macOS, Microsoft Windows, CI/CD, Atlassian JIRA, Atlassian Confluence, Ansible

      - layout: top
        title: Grundkenntnisse
        description: Java, iOS, Android, Python, Swift

  - title: Sprachen
    layout: list
    content:
      - layout: top
        title: Muttersprache
        description: Deutsch

      - layout: top
        title: fliessend
        description: Englisch

      - layout: top
        title: Grundkenntnisse
        description: Französich

  - title: Freizeit
    layout: text
    content: | # - Rennrad fahren
      - Reisen
      - Fotografie
      - Plane Spotting
      - Ship Spotting

footer_show_references: false

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
